name: Gerar base batimetrica

on:
  workflow_dispatch:

jobs:
  teste:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar repositorio
        uses: actions/checkout@v4

      - name: Testar workflow
        run: echo "Workflow funcionando corretamente."
